name: Swift

on: [push]

jobs:

    linux-swift:
        name: Linux
        runs-on: ubuntu-20.04
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Install Swift
          uses: slashmo/install-swift@v0.3.0
          with:
            version: swift-5.7.3
        - name: Swift Version
          run: swift --version
        - name: Install Dependencies
          run: sudo apt update && sudo apt install libssl-dev -y
        - name: Build (Debug)
          run: swift build -c debug
        - name: Build (Release)
          run: swift build -c release
        - name: Test (Debug)
          run: swift test --configuration debug --enable-code-coverage
        - name: Test (Release)
          run: swift test --configuration release -Xswiftc -enable-testing --enable-code-coverage
        - name: Coverage Report
          uses: maxep/spm-lcov-action@0.3.1
