name: Swift

on: [push]

jobs:

    linux-swift:
        name: Linux (Swift 5.6.1)
        runs-on: ubuntu-20.04
        container: swift:5.6.1-focal
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Swift Version
          run: swift --version
        - name: Install Dependencies
          run: apt update && apt install libssl-dev -y
        - name: Build (Debug)
          run: swift build -c debug
        - name: Build (Release)
          run: swift build -c release
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: swiftpm-build-ubuntu-x86_64
            path: .build/*/*.xctest
        - name: Coverage Report
          uses: maxep/spm-lcov-action@0.3.1
